  default: &default
    adapter: postgresql
    host: <%= ENV.fetch("DATABASE_HOST", nil) %>
    port: <%= ENV.fetch("DATABASE_PORT", nil) %>
    pool: 5
    timeout: 5000
    user: <%= ENV.fetch("DATABASE_USER", nil) %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", nil) %>

  development:
    <<: *default
    database: elpis_development

  test:
    <<: *default
    database: elpis_test
