  default: &default
    adapter: postgresql
    host: localhost
    port: 5432
    pool: 5
    timeout: 5000
    user: backend
    password: backend

  development:
    <<: *default
    database: backend_development

  test:
    <<: *default
    database: backend_test
    host: postgres
